name: PatchORE
version: ${version}
main: org.openredstone.patchore.PatchORE
api-version: '1.21'
depend: [ProtocolLib, NBTAPI]
load: STARTUP
authors: [ "Nickster258", "PaukkuPalikka", "QSmally", "StackDoubleFlow", "ShayHi", "Waffle [Wueffi]" ]
description: A plugin with various patches specifically designed for ORE
